//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace <Namespace> {
    
    
    public partial class <TableName> {
        

        protected global::System.Web.UI.WebControls.Label lblTitulo;
        protected global::System.Web.UI.WebControls.Label lblLinea;
		<Fields>
        protected global::System.Web.UI.WebControls.<ControlByDataType> <PrefixControl><FieldName>;
		protected global::System.Web.UI.WebControls.Label lblRequired<FieldName>;		
		</Fields>
            
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
		protected global::System.Web.UI.WebControls.Button btnConsultar;
  
        protected global::System.Web.UI.WebControls.Button btnGuardar;
		protected global::System.Web.UI.WebControls.Button btnCancelar;
		protected global::System.Web.UI.WebControls.Button btnEliminar;
        
        protected global::System.Web.UI.WebControls.GridView gv<TableName>;
    }
}
